using MediaEngine.Domain;
using MediaEngine.Domain.Contracts;
using MediaEngine.Domain.Entities;
using MediaEngine.Domain.Enums;
using MediaEngine.Providers.Helpers;
using MediaEngine.Providers.Models;

namespace MediaEngine.Providers.Tests;

/// <summary>
/// Tests for identity pipeline entities, state machine, and stage outcome logic.
/// </summary>
public sealed class IdentityPipelineTests
{
    // ── IdentityJob state defaults ──────────────────────────────────────────

    [Fact]
    public void IdentityJob_DefaultState_IsQueued()
    {
        var job = new IdentityJob { EntityId = Guid.NewGuid(), MediaType = "Books" };

        Assert.Equal("Queued", job.State);
        Assert.Equal("Quick", job.Pass);
        Assert.Equal(0, job.AttemptCount);
        Assert.Null(job.SelectedCandidateId);
        Assert.Null(job.ResolvedQid);
        Assert.Null(job.LastError);
    }

    [Fact]
    public void IdentityJob_IdAutoGenerated()
    {
        var job1 = new IdentityJob();
        var job2 = new IdentityJob();

        Assert.NotEqual(job1.Id, job2.Id);
        Assert.NotEqual(Guid.Empty, job1.Id);
    }

    // ── RetailMatchCandidate defaults ────────────────────────────────────────

    [Fact]
    public void RetailMatchCandidate_DefaultOutcome_IsRejected()
    {
        var candidate = new RetailMatchCandidate { JobId = Guid.NewGuid(), Title = "Test" };

        Assert.Equal("Rejected", candidate.Outcome);
        Assert.Equal(0.0, candidate.ScoreTotal);
    }

    [Fact]
    public void RetailMatchCandidate_FullConstruction_AllFieldsSet()
    {
        var jobId = Guid.NewGuid();
        var providerId = Guid.NewGuid();

        var candidate = new RetailMatchCandidate
        {
            JobId = jobId,
            ProviderId = providerId,
            ProviderName = "Apple Books",
            ProviderItemId = "12345",
            Rank = 1,
            Title = "Dune",
            Creator = "Frank Herbert",
            Year = "1965",
            ScoreTotal = 0.92,
            ScoreBreakdownJson = """{"title":0.45,"author":0.35,"year":0.10,"format":0.02}""",
            BridgeIdsJson = """{"isbn_13":"978-0441172719"}""",
            Description = "A science fiction novel",
            ImageUrl = "https://example.com/cover.jpg",
            Outcome = "AutoAccepted",
        };

        Assert.Equal(jobId, candidate.JobId);
        Assert.Equal("Dune", candidate.Title);
        Assert.Equal(0.92, candidate.ScoreTotal);
        Assert.Equal("AutoAccepted", candidate.Outcome);
    }

    // ── WikidataBridgeCandidate defaults ─────────────────────────────────────

    [Fact]
    public void WikidataBridgeCandidate_DefaultOutcome_IsRejected()
    {
        var candidate = new WikidataBridgeCandidate { JobId = Guid.NewGuid(), Qid = "Q190159" };

        Assert.Equal("Rejected", candidate.Outcome);
        Assert.False(candidate.IsExactMatch);
    }

    [Fact]
    public void WikidataBridgeCandidate_BridgeMatch_IsExact()
    {
        var candidate = new WikidataBridgeCandidate
        {
            JobId = Guid.NewGuid(),
            Qid = "Q190159",
            Label = "Dune",
            MatchedBy = "bridge_id",
            BridgeIdType = BridgeIdKeys.Isbn13,
            IsExactMatch = true,
            ScoreTotal = 1.0,
            Outcome = "AutoAccepted",
        };

        Assert.True(candidate.IsExactMatch);
        Assert.Equal(1.0, candidate.ScoreTotal);
        Assert.Equal("bridge_id", candidate.MatchedBy);
    }

    [Fact]
    public void WikidataBridgeCandidate_TextFallback_NotExact()
    {
        var candidate = new WikidataBridgeCandidate
        {
            JobId = Guid.NewGuid(),
            Qid = "Q190159",
            Label = "Dune",
            MatchedBy = "text_reconciliation",
            IsExactMatch = false,
            ScoreTotal = 0.75,
            Outcome = "AutoAccepted",
        };

        Assert.False(candidate.IsExactMatch);
        Assert.Equal("text_reconciliation", candidate.MatchedBy);
    }

    // ── IdentityJobState enum ───────────────────────────────────────────────

    [Fact]
    public void IdentityJobState_AllStatesExist()
    {
        // Verify the state machine is complete
        var states = Enum.GetValues<IdentityJobState>();

        Assert.Contains(IdentityJobState.Queued, states);
        Assert.Contains(IdentityJobState.RetailSearching, states);
        Assert.Contains(IdentityJobState.RetailMatched, states);
        Assert.Contains(IdentityJobState.RetailMatchedNeedsReview, states);
        Assert.Contains(IdentityJobState.RetailNoMatch, states);
        Assert.Contains(IdentityJobState.BridgeSearching, states);
        Assert.Contains(IdentityJobState.QidResolved, states);
        Assert.Contains(IdentityJobState.QidNeedsReview, states);
        Assert.Contains(IdentityJobState.QidNoMatch, states);
        Assert.Contains(IdentityJobState.Hydrating, states);
        Assert.Contains(IdentityJobState.Completed, states);
        Assert.Contains(IdentityJobState.Failed, states);
    }

    // ── ReviewTrigger constants ─────────────────────────────────────────────

    [Fact]
    public void ReviewTrigger_RetailAndBridgeTriggers_Exist()
    {
        Assert.Equal("RetailMatchFailed", ReviewTrigger.RetailMatchFailed);
        Assert.Equal("RetailMatchAmbiguous", ReviewTrigger.RetailMatchAmbiguous);
        Assert.Equal("WikidataBridgeFailed", ReviewTrigger.WikidataBridgeFailed);
    }

    // ── Strict retail gate (design verification) ────────────────────────────

    [Fact]
    public void StrictRetailGate_WikidataBridgeWorkerStates_DoNotIncludeRetailNoMatch()
    {
        // The WikidataBridgeWorker only leases these states:
        var bridgeWorkerStates = new[]
        {
            IdentityJobState.RetailMatched,
            IdentityJobState.RetailMatchedNeedsReview,
        };

        Assert.DoesNotContain(IdentityJobState.RetailNoMatch, bridgeWorkerStates);
        Assert.DoesNotContain(IdentityJobState.Queued, bridgeWorkerStates);
        Assert.DoesNotContain(IdentityJobState.Failed, bridgeWorkerStates);
    }

    // ── Retail scoring outcome thresholds ────────────────────────────────────

    [Theory]
    [InlineData(0.90, "AutoAccepted")]
    [InlineData(0.85, "AutoAccepted")]
    [InlineData(0.70, "Ambiguous")]
    [InlineData(0.50, "Ambiguous")]
    [InlineData(0.49, "Rejected")]
    [InlineData(0.30, "Rejected")]
    [InlineData(0.00, "Rejected")]
    public void RetailOutcome_ThresholdLogic_CorrectOutcome(double score, string expectedOutcome)
    {
        // These thresholds match RetailMatchWorker's logic:
        // ≥ 0.85 = AutoAccepted, ≥ ambiguousThreshold (0.50) = Ambiguous, else Rejected
        double autoAcceptThreshold = 0.85;
        double ambiguousThreshold = 0.50;

        string outcome;
        if (score >= autoAcceptThreshold)
            outcome = "AutoAccepted";
        else if (score >= ambiguousThreshold)
            outcome = "Ambiguous";
        else
            outcome = "Rejected";

        Assert.Equal(expectedOutcome, outcome);
    }
}
