namespace MediaEngine.Domain.Models;

/// <summary>
/// A user's taste profile built from their library patterns.
/// Stored in the user_taste_profiles table as JSON.
/// </summary>
public sealed class TasteProfile
{
    /// <summary>Profile owner's user ID.</summary>
    public Guid UserId { get; init; }

    /// <summary>Genre distribution as percentages (e.g. {"sci-fi": 0.35, "thriller": 0.20}).</summary>
    public IReadOnlyDictionary<string, double> GenreDistribution { get; init; } = new Dictionary<string, double>();

    /// <summary>Era preferences (e.g. {"1970s": 0.15, "2020s": 0.40}).</summary>
    public IReadOnlyDictionary<string, double> EraPreferences { get; init; } = new Dictionary<string, double>();

    /// <summary>Media type mix (e.g. {"Books": 0.50, "Movies": 0.30}).</summary>
    public IReadOnlyDictionary<string, double> MediaTypeMix { get; init; } = new Dictionary<string, double>();

    /// <summary>Mood/vibe preferences from consumed items.</summary>
    public IReadOnlyDictionary<string, double> MoodPreferences { get; init; } = new Dictionary<string, double>();

    /// <summary>Human-readable profile summary generated by the LLM.</summary>
    public string? Summary { get; init; }

    /// <summary>When the profile was last updated.</summary>
    public DateTimeOffset LastUpdatedAt { get; init; }
}
