using MediaEngine.Contracts.Items;
using MediaEngine.Contracts.Review;
using MediaEngine.Web.Models.ViewDTOs;

namespace MediaEngine.Web.Services.Integration;

internal static class CurationContractMapper
{
    public static MediaEngine.Web.Models.ViewDTOs.BatchLibraryItemResponse ToViewModel(
        this MediaEngine.Contracts.Items.BatchLibraryItemResponse source) => new()
    {
        ProcessedCount = source.ProcessedCount,
        TotalRequested = source.TotalRequested,
        Message = source.Message,
    };

    public static LibraryCatalogPageResponse ToViewModel(this LibraryItemsPageDto source) => new()
    {
        Items = source.Items.Select(ToViewModel).ToList(),
        TotalCount = source.TotalCount,
        HasMore = source.HasMore,
    };

    public static LibraryCatalogItemViewModel ToViewModel(this LibraryCatalogItemDto source) => new()
    {
        EntityId = source.EntityId,
        Title = source.Title,
        Year = source.Year,
        MediaType = source.MediaType,
        CoverUrl = source.CoverUrl,
        BackgroundUrl = source.BackgroundUrl,
        BannerUrl = source.BannerUrl,
        MatchSource = source.MatchSource,
        MatchMethod = source.MatchMethod,
        Confidence = source.Confidence,
        Status = source.Status,
        HasDuplicate = source.HasDuplicate,
        DuplicateOf = source.DuplicateOf,
        ReviewItemId = source.ReviewItemId,
        ReviewTrigger = source.ReviewTrigger,
        HasUserLocks = source.HasUserLocks,
        CreatedAt = source.CreatedAt,
        FileName = source.FileName,
        FileSizeBytes = source.FileSizeBytes,
        FilePath = source.FilePath,
        Author = source.Author,
        Director = source.Director,
        Artist = source.Artist,
        Series = source.Series,
        SeriesPosition = source.SeriesPosition,
        Narrator = source.Narrator,
        Genre = source.Genre,
        Runtime = source.Runtime,
        Rating = source.Rating,
        Album = source.Album,
        TrackNumber = source.TrackNumber,
        Season = source.SeasonNumber,
        Episode = source.EpisodeNumber,
        Duration = source.Duration,
        ShowName = source.ShowName,
        EpisodeTitle = source.EpisodeTitle,
        Network = source.Network,
        TopCast = source.TopCast,
        WikidataStatus = source.WikidataStatus,
        WikidataMatch = source.WikidataMatch,
        RetailMatch = source.RetailMatch,
        RetailMatchDetail = source.RetailMatchDetail,
        WikidataQid = source.WikidataQid,
        HeroUrl = source.HeroUrl,
        PipelineStep = source.PipelineStep,
        LibraryVisibility = source.LibraryVisibility,
        IsReadyForLibrary = source.IsReadyForLibrary,
        ArtworkState = source.ArtworkState,
        ArtworkSource = source.ArtworkSource,
        ArtworkSettledAt = source.ArtworkSettledAt,
    };

    public static LibraryItemDetailViewModel ToViewModel(this LibraryItemDetailDto source) => new()
    {
        EntityId = source.EntityId,
        Title = source.Title,
        Year = source.Year,
        MediaType = source.MediaType,
        CoverUrl = source.CoverUrl,
        BackgroundUrl = source.BackgroundUrl,
        BannerUrl = source.BannerUrl,
        HeroUrl = source.HeroUrl,
        Confidence = source.Confidence,
        Status = source.Status,
        MatchSource = source.MatchSource,
        MatchMethod = source.MatchMethod,
        Author = source.Author,
        Album = source.Album,
        Artist = source.Artist,
        Director = source.Director,
        Writer = source.Writer,
        Cast = source.Cast,
        Language = source.Language,
        Genre = source.Genre,
        Runtime = source.Runtime,
        Description = source.Description,
        Tagline = source.Tagline,
        Series = source.Series,
        SeriesPosition = source.SeriesPosition,
        ShowName = source.ShowName,
        SeasonNumber = source.SeasonNumber,
        EpisodeNumber = source.EpisodeNumber,
        EpisodeTitle = source.EpisodeTitle,
        ReleaseDate = source.ReleaseDate,
        Narrator = source.Narrator,
        Rating = source.Rating,
        WikidataQid = source.WikidataQid,
        WikidataStatus = source.WikidataStatus,
        FileName = source.FileName,
        FilePath = source.FilePath,
        FileSizeBytes = source.FileSizeBytes,
        ContentHash = source.ContentHash,
        ReviewItemId = source.ReviewItemId,
        ReviewTrigger = source.ReviewTrigger,
        ReviewDetail = source.ReviewDetail,
        CandidatesJson = source.CandidatesJson,
        HasUserLocks = source.HasUserLocks,
        MatchLevel = source.MatchLevel,
        CanonicalValues = source.CanonicalValues.Select(value => new MediaEngine.Web.Models.ViewDTOs.LibraryItemCanonicalValueDto
        {
            Key = value.Key,
            Value = value.Value,
            IsConflicted = value.IsConflicted,
            WinningProviderId = value.WinningProviderId,
            NeedsReview = value.NeedsReview,
            LastScoredAt = value.LastScoredAt,
        }).ToList(),
        ClaimHistory = source.ClaimHistory.Select(claim => new MediaEngine.Web.Models.ViewDTOs.LibraryItemClaimRecordDto
        {
            Id = claim.Id,
            ClaimKey = claim.ClaimKey,
            ClaimValue = claim.ClaimValue,
            ProviderId = claim.ProviderId,
            Confidence = claim.Confidence,
            IsUserLocked = claim.IsUserLocked,
            ClaimedAt = claim.ClaimedAt,
        }).ToList(),
        BridgeIds = source.BridgeIds,
        PipelineStep = source.PipelineStep,
        LibraryVisibility = source.LibraryVisibility,
        IsReadyForLibrary = source.IsReadyForLibrary,
        ArtworkState = source.ArtworkState,
        ArtworkSource = source.ArtworkSource,
        ArtworkSettledAt = source.ArtworkSettledAt,
        UniverseSummary = source.UniverseSummary is null ? null : new UniverseSummaryViewModel
        {
            UniverseStatus = source.UniverseSummary.UniverseStatus,
            UniverseName = source.UniverseSummary.UniverseName,
            UniverseQid = source.UniverseSummary.UniverseQid,
            NarrativeRootQid = source.UniverseSummary.NarrativeRootQid,
            Stage3Status = source.UniverseSummary.Stage3Status,
            Stage3EnrichedAt = source.UniverseSummary.Stage3EnrichedAt,
            EntityCount = source.UniverseSummary.EntityCount,
            RelationshipCount = source.UniverseSummary.RelationshipCount,
            PortraitCount = source.UniverseSummary.PortraitCount,
        },
        PlaybackSummary = source.PlaybackSummary is null ? null : new PlaybackTechnicalSummaryViewModel
        {
            VideoResolutionLabel = source.PlaybackSummary.VideoResolutionLabel,
            VideoCodec = source.PlaybackSummary.VideoCodec,
            AudioLanguage = source.PlaybackSummary.AudioLanguage,
            AudioCodec = source.PlaybackSummary.AudioCodec,
            AudioChannels = source.PlaybackSummary.AudioChannels,
            SubtitleSummary = source.PlaybackSummary.SubtitleSummary,
            AudioLanguages = source.PlaybackSummary.AudioLanguages.ToList(),
            SubtitleLanguages = source.PlaybackSummary.SubtitleLanguages.ToList(),
        },
    };

    public static ReviewItemViewModel ToViewModel(this ReviewItemDto source) => new()
    {
        Id = source.Id,
        EntityId = source.EntityId,
        EntityType = source.EntityType,
        Trigger = source.Trigger,
        Status = source.Status,
        ProposedCollectionId = Guid.TryParse(source.ProposedCollectionId, out var collectionId) ? collectionId : null,
        ConfidenceScore = source.ConfidenceScore,
        CandidatesJson = source.CandidatesJson,
        Detail = source.Detail,
        CreatedAt = source.CreatedAt,
        ResolvedAt = source.ResolvedAt,
        ResolvedBy = source.ResolvedBy,
        MediaType = source.MediaType,
        EntityTitle = source.EntityTitle,
        CoverUrl = source.CoverUrl,
        BridgeIdentifiers = source.BridgeIdentifiers,
    };
}
