namespace MediaEngine.AI.Configuration;

public static class AiModelCatalogDefaults
{
    public static Dictionary<string, AiModelCatalogEntry> CreateCatalog() =>
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["qwen3_0_6b_q8"] = Text(
                displayName: "Qwen3 0.6B Q8",
                family: "Qwen3",
                provider: "Qwen",
                license: "Apache-2.0",
                status: "candidate",
                selectionTier: "primary-small",
                roles: ["text_fast"],
                file: "Qwen3-0.6B-Q8_0.gguf",
                downloadUrl: "https://huggingface.co/Qwen/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q8_0.gguf",
                sourceUrl: "https://huggingface.co/Qwen/Qwen3-0.6B-GGUF",
                sizeMb: 639,
                parametersB: 0.6,
                quantization: "Q8_0",
                contextLength: 32768,
                cjk: true,
                benchmarkSuite: "text_instant",
                rationale: "Smallest official Qwen3 GGUF; preferred first-pass candidate for instant JSON tasks."),

            ["qwen3_1_7b_q8"] = Text(
                displayName: "Qwen3 1.7B Q8",
                family: "Qwen3",
                provider: "Qwen",
                license: "Apache-2.0",
                status: "candidate",
                selectionTier: "primary-quality",
                roles: ["text_quality", "text_enrichment"],
                file: "Qwen3-1.7B-Q8_0.gguf",
                downloadUrl: "https://huggingface.co/Qwen/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q8_0.gguf",
                sourceUrl: "https://huggingface.co/Qwen/Qwen3-1.7B-GGUF",
                sizeMb: 1830,
                parametersB: 1.7,
                quantization: "Q8_0",
                contextLength: 32768,
                cjk: true,
                benchmarkSuite: "text_ingestion",
                rationale: "Default quality candidate because it is smaller than the old 3B role and keeps strong multilingual coverage."),

            ["qwen3_4b_q4"] = Text(
                displayName: "Qwen3 4B Q4_K_M",
                family: "Qwen3",
                provider: "Qwen",
                license: "Apache-2.0",
                status: "candidate",
                selectionTier: "primary-scholar",
                roles: ["text_scholar", "text_cjk", "text_enrichment"],
                file: "Qwen3-4B-Q4_K_M.gguf",
                downloadUrl: "https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
                sourceUrl: "https://huggingface.co/Qwen/Qwen3-4B-GGUF",
                sizeMb: 2500,
                parametersB: 4.0,
                quantization: "Q4_K_M",
                contextLength: 32768,
                cjk: true,
                benchmarkSuite: "text_enrichment",
                rationale: "Preferred high-tier cap: much smaller than the old 8B model while preserving long context and multilingual support."),

            ["llama32_1b_q4"] = Text(
                displayName: "Llama 3.2 1B Instruct Q4_K_M",
                family: "Llama 3.2",
                provider: "Meta",
                license: "Llama 3.2 Community",
                status: "baseline",
                selectionTier: "legacy-baseline",
                roles: ["text_fast"],
                file: "llama-3.2-1b-instruct.Q4_K_M.gguf",
                downloadUrl: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
                sourceUrl: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF",
                sizeMb: 750,
                parametersB: 1.0,
                quantization: "Q4_K_M",
                contextLength: 2048,
                cjk: false,
                benchmarkSuite: "text_instant",
                rationale: "Legacy fast baseline retained for direct regression comparison."),

            ["llama32_3b_q4"] = Text(
                displayName: "Llama 3.2 3B Instruct Q4_K_M",
                family: "Llama 3.2",
                provider: "Meta",
                license: "Llama 3.2 Community",
                status: "baseline",
                selectionTier: "legacy-baseline",
                roles: ["text_quality"],
                file: "llama-3.2-3b-instruct.Q4_K_M.gguf",
                downloadUrl: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
                sourceUrl: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF",
                sizeMb: 2000,
                parametersB: 3.0,
                quantization: "Q4_K_M",
                contextLength: 4096,
                cjk: false,
                benchmarkSuite: "text_ingestion",
                rationale: "Legacy quality baseline retained until Qwen3 passes the same fixtures."),

            ["gemma4_e2b_it"] = Text(
                displayName: "Gemma 4 E2B IT",
                family: "Gemma 4",
                provider: "Google",
                license: "Apache-2.0",
                status: "candidate",
                selectionTier: "multimodal-candidate",
                roles: ["text_quality", "text_enrichment"],
                file: "gemma-4-E2B-it-Q8_0.gguf",
                downloadUrl: "https://huggingface.co/ggml-org/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q8_0.gguf",
                sourceUrl: "https://huggingface.co/ggml-org/gemma-4-E2B-it-GGUF",
                sizeMb: 5000,
                parametersB: 5.1,
                effectiveParametersB: 2.3,
                quantization: "Q8_0",
                contextLength: 256000,
                cjk: true,
                benchmarkSuite: "text_enrichment",
                rationale: "Useful for multimodal/long-context validation, but not the smallest default."),

            ["gemma4_e4b_it"] = Text(
                displayName: "Gemma 4 E4B IT",
                family: "Gemma 4",
                provider: "Google",
                license: "Apache-2.0",
                status: "candidate",
                selectionTier: "multimodal-candidate",
                roles: ["text_scholar", "text_enrichment"],
                file: "gemma-4-E4B-it-Q4_K_M.gguf",
                downloadUrl: "https://huggingface.co/ggml-org/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf",
                sourceUrl: "https://huggingface.co/ggml-org/gemma-4-E4B-it-GGUF",
                sizeMb: 5340,
                parametersB: 8.0,
                effectiveParametersB: 4.5,
                quantization: "Q4_K_M",
                contextLength: 256000,
                cjk: true,
                benchmarkSuite: "text_enrichment",
                rationale: "Escalate here only if 4B-class Qwen3 fails long-context or multimodal fixtures.",
                experimentalMultimodal: true),

            ["gemma4_12b_it"] = Text(
                displayName: "Gemma 4 12B IT",
                family: "Gemma 4",
                provider: "Google",
                license: "Apache-2.0",
                status: "escalation",
                selectionTier: "lab-escalation",
                roles: ["text_scholar"],
                file: "gemma-4-12b-it-Q4_K_M.gguf",
                downloadUrl: "https://huggingface.co/ggml-org/gemma-4-12b-it-GGUF/resolve/main/gemma-4-12b-it-Q4_K_M.gguf",
                sourceUrl: "https://huggingface.co/ggml-org/gemma-4-12b-it-GGUF",
                sizeMb: 7600,
                parametersB: 12.0,
                quantization: "Q4_K_M",
                contextLength: 256000,
                cjk: true,
                benchmarkSuite: "text_enrichment",
                rationale: "Optional lab model; never select by default unless smaller models fail documented gates.",
                experimentalMultimodal: true),

            ["whisper_medium"] = Audio(
                displayName: "Whisper Medium",
                family: "Whisper",
                provider: "OpenAI / whisper.cpp",
                license: "MIT",
                status: "current",
                selectionTier: "sync-default",
                roles: ["audio"],
                file: "ggml-medium.bin",
                downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
                sourceUrl: "https://github.com/openai/whisper",
                sizeMb: 1500,
                parametersB: 0.77,
                quantization: "ggml",
                benchmarkSuite: "audio_sync",
                rationale: "Current .NET-compatible sync baseline with timestamped segment output."),

            ["distil_whisper_large_v3"] = Audio(
                displayName: "Distil-Whisper large-v3",
                family: "Distil-Whisper",
                provider: "Distil-Whisper",
                license: "MIT",
                status: "candidate",
                selectionTier: "english-audio-candidate",
                roles: ["audio"],
                file: "ggml-distil-large-v3.bin",
                downloadUrl: "https://huggingface.co/distil-whisper/distil-large-v3-ggml/resolve/main/ggml-distil-large-v3.bin",
                sourceUrl: "https://huggingface.co/distil-whisper/distil-large-v3",
                sizeMb: 1500,
                parametersB: 0.756,
                quantization: "ggml",
                benchmarkSuite: "audio_sync",
                rationale: "English-first candidate that keeps Whisper-compatible tooling and may reduce runtime impact."),

            ["whisper_large_v3_turbo"] = Audio(
                displayName: "Whisper large-v3-turbo",
                family: "Whisper",
                provider: "OpenAI",
                license: "MIT",
                status: "candidate",
                selectionTier: "multilingual-audio-candidate",
                roles: ["audio"],
                file: "ggml-large-v3-turbo.bin",
                downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
                sourceUrl: "https://huggingface.co/openai/whisper-large-v3-turbo",
                sizeMb: 1620,
                parametersB: 0.809,
                quantization: "ggml",
                benchmarkSuite: "audio_sync",
                rationale: "Multilingual Whisper-family candidate that may improve quality/speed while preserving timestamp semantics."),

            ["parakeet_tdt_0_6b_v3"] = ExperimentalAudio(
                displayName: "NVIDIA Parakeet TDT 0.6B v3",
                family: "Parakeet",
                provider: "NVIDIA",
                license: "CC-BY-4.0",
                roles: ["audio"],
                sourceUrl: "https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3",
                sizeMb: 1200,
                parametersB: 0.6,
                rationale: "Promising word-timestamp ASR, but requires non-Whisper runtime integration before it can be a default."),

            ["qwen3_asr_0_6b"] = ExperimentalAudio(
                displayName: "Qwen3-ASR 0.6B",
                family: "Qwen3-ASR",
                provider: "Qwen",
                license: "Apache-2.0",
                roles: ["audio"],
                sourceUrl: "https://huggingface.co/Qwen/Qwen3-ASR-0.6B",
                sizeMb: 1400,
                parametersB: 0.6,
                rationale: "Future ASR candidate; timestamp sync requires the separate Qwen3 forced aligner path."),
        };

    public static Dictionary<string, AiRoleRequirement> CreateRoleRequirements() =>
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["text_fast"] = new()
            {
                Description = "Instant UI-facing summaries, intent parsing, and small structured transforms.",
                RequiredCapabilities = ["text_input", "text_output", "structured_json", "gbnf"],
                PreferredCatalogKeys = ["qwen3_0_6b_q8", "llama32_1b_q4", "qwen3_1_7b_q8"],
                FallbackCatalogKeys = ["llama32_1b_q4"],
                MaxDefaultSizeMB = 1000,
                TargetWarmLatencyMs = 1500,
                MaxBackgroundLatencyMs = 3000,
                MinJsonValidityRate = 0.99,
                MinTaskPassRate = 0.92,
                BenchmarkSuite = "text_instant",
            },
            ["text_quality"] = new()
            {
                Description = "Background ingestion reasoning, QID disambiguation, and vibe tagging.",
                RequiredCapabilities = ["text_input", "text_output", "structured_json", "gbnf"],
                PreferredCatalogKeys = ["qwen3_1_7b_q8", "llama32_3b_q4", "qwen3_4b_q4", "gemma4_e2b_it"],
                FallbackCatalogKeys = ["llama32_3b_q4", "qwen3_4b_q4"],
                MaxDefaultSizeMB = 2200,
                TargetWarmLatencyMs = 5000,
                MaxBackgroundLatencyMs = 10000,
                MinJsonValidityRate = 0.99,
                MinTaskPassRate = 0.94,
                BenchmarkSuite = "text_ingestion",
            },
            ["text_scholar"] = new()
            {
                Description = "Long-context enrichment and hard relationship extraction.",
                RequiredCapabilities = ["text_input", "text_output", "structured_json", "gbnf"],
                PreferredCatalogKeys = ["qwen3_4b_q4", "gemma4_e4b_it", "gemma4_12b_it"],
                FallbackCatalogKeys = ["qwen3_1_7b_q8", "llama32_3b_q4"],
                MaxDefaultSizeMB = 3000,
                TargetWarmLatencyMs = 10000,
                MaxBackgroundLatencyMs = 30000,
                MinJsonValidityRate = 0.99,
                MinTaskPassRate = 0.95,
                BenchmarkSuite = "text_enrichment",
            },
            ["text_cjk"] = new()
            {
                Description = "CJK and multilingual analysis without promoting a larger general model.",
                RequiredCapabilities = ["text_input", "text_output", "structured_json", "gbnf", "cjk"],
                PreferredCatalogKeys = ["qwen3_1_7b_q8", "qwen3_4b_q4"],
                FallbackCatalogKeys = ["qwen3_4b_q4"],
                MaxDefaultSizeMB = 3000,
                TargetWarmLatencyMs = 10000,
                MaxBackgroundLatencyMs = 30000,
                MinJsonValidityRate = 0.99,
                MinTaskPassRate = 0.93,
                BenchmarkSuite = "text_multilingual",
            },
            ["audio"] = new()
            {
                Description = "Transcription, language detection, audiobook sync, and subtitle timing.",
                RequiredCapabilities = ["audio_input", "text_output", "timestamp_segments", "sync_grade"],
                PreferredCatalogKeys = ["whisper_medium", "distil_whisper_large_v3", "whisper_large_v3_turbo"],
                FallbackCatalogKeys = ["whisper_medium"],
                MaxDefaultSizeMB = 1800,
                TargetWarmLatencyMs = 0,
                MaxBackgroundLatencyMs = 0,
                MinJsonValidityRate = 0,
                MinTaskPassRate = 0.95,
                BenchmarkSuite = "audio_sync",
            },
        };

    private static AiModelCatalogEntry Text(
        string displayName,
        string family,
        string provider,
        string license,
        string status,
        string selectionTier,
        List<string> roles,
        string file,
        string downloadUrl,
        string sourceUrl,
        int sizeMb,
        double parametersB,
        string quantization,
        int contextLength,
        bool cjk,
        string benchmarkSuite,
        string rationale,
        double? effectiveParametersB = null,
        bool experimentalMultimodal = false) =>
        new()
        {
            DisplayName = displayName,
            Family = family,
            Provider = provider,
            License = license,
            Runtime = "LLamaSharp/GGUF",
            Status = status,
            SelectionTier = selectionTier,
            IntendedRoles = roles,
            File = file,
            DownloadUrl = downloadUrl,
            SourceUrl = sourceUrl,
            SizeMB = sizeMb,
            ParametersB = parametersB,
            EffectiveParametersB = effectiveParametersB,
            Quantization = quantization,
            ContextLength = contextLength,
            Capabilities = new()
            {
                TextInput = true,
                TextOutput = true,
                StructuredJson = true,
                Gbnf = true,
                Multilingual = true,
                Cjk = cjk,
                ImageInput = experimentalMultimodal,
                AudioInput = experimentalMultimodal,
                ExperimentalMultimodal = experimentalMultimodal,
            },
            Validation = new()
            {
                TargetWarmLatencyMs = benchmarkSuite == "text_instant" ? 1500 : 10000,
                MaxWarmLatencyMs = benchmarkSuite == "text_instant" ? 3000 : 30000,
                MinJsonValidityRate = 0.99,
                MinTaskPassRate = benchmarkSuite == "text_enrichment" ? 0.95 : 0.92,
                MaxHallucinationRate = 0.02,
                BenchmarkSuite = benchmarkSuite,
            },
            SelectionRationale = rationale,
            IntegrationNotes = experimentalMultimodal
                ? "Treat multimodal input as experimental until the local runtime exposes Tuvima-compatible adapters."
                : "Use through the existing GGUF text inference path.",
        };

    private static AiModelCatalogEntry Audio(
        string displayName,
        string family,
        string provider,
        string license,
        string status,
        string selectionTier,
        List<string> roles,
        string file,
        string downloadUrl,
        string sourceUrl,
        int sizeMb,
        double parametersB,
        string quantization,
        string benchmarkSuite,
        string rationale) =>
        new()
        {
            DisplayName = displayName,
            Family = family,
            Provider = provider,
            License = license,
            Runtime = "Whisper.net/whisper.cpp",
            Status = status,
            SelectionTier = selectionTier,
            IntendedRoles = roles,
            File = file,
            DownloadUrl = downloadUrl,
            SourceUrl = sourceUrl,
            SizeMB = sizeMb,
            ParametersB = parametersB,
            Quantization = quantization,
            Capabilities = new()
            {
                AudioInput = true,
                TextOutput = true,
                TimestampSegments = true,
                SyncGrade = true,
                Multilingual = !displayName.Contains("Distil", StringComparison.OrdinalIgnoreCase),
            },
            Validation = new()
            {
                MinTaskPassRate = 0.95,
                MaxWer = 0.12,
                MaxTimestampDriftMs = 250,
                BenchmarkSuite = benchmarkSuite,
            },
            SelectionRationale = rationale,
            IntegrationNotes = "Compatible with the existing Whisper timestamped segment abstraction.",
        };

    private static AiModelCatalogEntry ExperimentalAudio(
        string displayName,
        string family,
        string provider,
        string license,
        List<string> roles,
        string sourceUrl,
        int sizeMb,
        double parametersB,
        string rationale) =>
        new()
        {
            DisplayName = displayName,
            Family = family,
            Provider = provider,
            License = license,
            Runtime = "external-asr",
            Status = "experimental",
            SelectionTier = "experimental-audio",
            IntendedRoles = roles,
            SourceUrl = sourceUrl,
            SizeMB = sizeMb,
            ParametersB = parametersB,
            Capabilities = new()
            {
                AudioInput = true,
                TextOutput = true,
                TimestampSegments = true,
                WordTimestamps = true,
                SyncGrade = true,
                Multilingual = true,
            },
            Validation = new()
            {
                MinTaskPassRate = 0.95,
                MaxWer = 0.12,
                MaxTimestampDriftMs = 250,
                BenchmarkSuite = "audio_sync",
            },
            SelectionRationale = rationale,
            IntegrationNotes = "Do not promote until a local runtime adapter exists and audio sync fixtures pass.",
        };
}
